apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: idp-postgres-credentials
  namespace: idp-platform
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: idp-postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: idp/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: idp/postgres
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: idp-s3-credentials
  namespace: idp-platform
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: idp-s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: idp/s3
        property: access_key_id
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: idp/s3
        property: secret_access_key
