version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    groups:
      spring:
        patterns:
          - "org.springframework*"
          - "org.springframework.boot*"
          - "org.springframework.cloud*"
          - "org.springframework.ai*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: "terraform"
    directory: "/infra/opentofu/aws"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
