-- Base de control (global de plataforma). Sin contenido documental ni PII.
CREATE TABLE planes (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    features JSONB NOT NULL,
    quota_limits JSONB NOT NULL
);

CREATE TABLE tenants (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    plan_id UUID NOT NULL REFERENCES planes(id),
    deletion_due_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_tenants_status ON tenants(status);

CREATE TABLE tenant_config (
    tenant_id UUID PRIMARY KEY REFERENCES tenants(id),
    data_kek_id VARCHAR(255),
    audit_kek_id VARCHAR(255),
    legal_hold BOOLEAN NOT NULL,
    settings JSONB NOT NULL
);

-- Ubicacion de los silos fisicos del tenant (sin secretos).
CREATE TABLE silo_location (
    tenant_id UUID PRIMARY KEY REFERENCES tenants(id),
    db_name VARCHAR(255) NOT NULL,
    bucket_name VARCHAR(255) NOT NULL,
    openbao_role VARCHAR(255) NOT NULL
);

-- Traza de pasos de aprovisionamiento y compensacion.
CREATE TABLE provisioning_step (
    id UUID PRIMARY KEY,
    seq BIGINT GENERATED ALWAYS AS IDENTITY,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    step VARCHAR(100) NOT NULL,
    action VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    detail VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_provisioning_step_tenant ON provisioning_step(tenant_id);

CREATE TABLE legal_hold (
    id UUID PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    reason_code VARCHAR(50) NOT NULL,
    applied_by VARCHAR(255) NOT NULL,
    applied_at TIMESTAMP WITH TIME ZONE NOT NULL,
    released_by VARCHAR(255),
    released_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_legal_hold_tenant ON legal_hold(tenant_id);

-- Borrado logico: deleted_at no nulo implica asignacion revocada o vencida.
CREATE TABLE role_assignment (
    id UUID PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    user_id VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    granted_by VARCHAR(255) NOT NULL,
    approved_by VARCHAR(255),
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    deleted_by VARCHAR(255),
    justification VARCHAR(500),
    delete_reason VARCHAR(50)
);
CREATE INDEX idx_role_assignment_lookup ON role_assignment(tenant_id, user_id);

CREATE TABLE quota_period (
    id UUID PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    metric_name VARCHAR(100) NOT NULL,
    period_start DATE NOT NULL,
    limit_value BIGINT NOT NULL,
    consumed BIGINT NOT NULL,
    threshold_notified BOOLEAN NOT NULL,
    CONSTRAINT uq_quota_period UNIQUE (tenant_id, metric_name, period_start)
);

CREATE TABLE consumption_record (
    id UUID PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    metric_name VARCHAR(100) NOT NULL,
    amount BIGINT NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_consumption_record_tenant ON consumption_record(tenant_id);

CREATE TABLE access_certification (
    id UUID PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    period_year INT NOT NULL,
    period_quarter INT NOT NULL,
    generated_by VARCHAR(255) NOT NULL,
    generated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    report_json TEXT NOT NULL,
    report_sha256 VARCHAR(64) NOT NULL,
    signature TEXT NOT NULL,
    key_id VARCHAR(255) NOT NULL
);
CREATE INDEX idx_access_certification_tenant ON access_certification(tenant_id);

CREATE TABLE outbox (
    seq bigint generated by default as identity,
    id UUID PRIMARY KEY,
    aggregate_type VARCHAR(100) NOT NULL,
    aggregate_id VARCHAR(255) NOT NULL,
    partition_key VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    payload JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_outbox_pending ON outbox(published_at, created_at);
