apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idp-app-local
  namespace: argocd
spec:
  project: idp
  source:
    repoURL: 'https://github.com/IngKevin95/IDP_ExtraccionDocumentos.git'
    path: deploy/helm/idp
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml  # cambiar a values-aws.yaml, values-gcp.yaml o values-azure.yaml según destino
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: idp-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true