create table document (
    id               uuid primary key,
    tenant_id        varchar(64) not null,
    hash_sha256      varchar(64),
    typology         varchar(32),
    radicado         varchar(64),
    version          integer not null default 1,
    status           varchar(32) not null,
    classification   varchar(32) not null default 'CONFIDENCIAL',
    object_store_key varchar(512),
    mime_type        varchar(64),
    file_size_bytes  bigint,
    uploaded_by      varchar(128),
    idempotency_key  varchar(128),
    created_at       timestamp with time zone not null,
    updated_at       timestamp with time zone not null,
    purged_at        timestamp with time zone
);

create unique index idx_doc_tenant_hash on document (tenant_id, hash_sha256);
create unique index idx_doc_tenant_business on document (tenant_id, typology, radicado, version);
create unique index idx_doc_tenant_idem on document (tenant_id, idempotency_key);
create index idx_doc_tenant_status on document (tenant_id, status);

create table page_artifact (
    id               uuid primary key,
    document_id      uuid not null references document (id) on delete cascade,
    kind             varchar(16) not null,
    page_number      integer not null,
    object_store_key varchar(512) not null,
    created_at       timestamp with time zone not null
);

create index idx_page_document on page_artifact (document_id);

create table outbox (
    seq bigint generated by default as identity,
    id            uuid primary key,
    partition_key varchar(255) not null,
    event_type    varchar(120) not null,
    tenant_id     uuid         not null,
    payload       text         not null,
    status        varchar(16)  not null default 'PENDING',
    attempts      integer      not null default 0,
    last_error    varchar(500),
    created_at    timestamp with time zone not null default now(),
    published_at  timestamp with time zone
);

create index idx_outbox_pending on outbox (status, created_at, id);

create table processed_event (
    event_id     uuid primary key,
    processed_at timestamp with time zone not null default now()
);
