-- Equivalente H2 del esquema del silo (la migracion real usa jsonb, trigger y indice parcial de PostgreSQL).
create table if not exists extraction (
    id               uuid primary key,
    document_id      uuid         not null,
    tenant_id        uuid         not null,
    status           varchar(32)  not null,
    typology_code    varchar(8),
    typology_version integer,
    model_version    varchar(255),
    prompt_version   varchar(100),
    overall_score    numeric(5, 4),
    tokens_in        integer      not null default 0,
    tokens_out       integer      not null default 0,
    cost_usd         numeric(12, 6) not null default 0,
    review_task_id   uuid,
    detail           varchar(200),
    created_at       timestamp with time zone not null default current_timestamp
);

create table if not exists field_value (
    id               uuid primary key,
    extraction_id    uuid         not null references extraction (id) on delete cascade,
    table_name       varchar(64),
    row_index        integer,
    field_name       varchar(64)  not null,
    value_text       clob,
    confidence_score numeric(5, 4),
    evidence_page    integer,
    evidence_quote   clob,
    bounding_box     clob,
    requires_review  boolean      not null default false,
    validation_error varchar(500)
);

create table if not exists ai_execution_record (
    id            uuid primary key,
    extraction_id uuid         not null references extraction (id),
    payload       clob         not null,
    signature     clob         not null,
    key_id        varchar(100) not null,
    created_at    timestamp with time zone not null default current_timestamp
);

create table if not exists outbox (
    seq bigint generated by default as identity,
    id            uuid primary key,
    partition_key varchar(255) not null,
    event_type    varchar(120) not null,
    tenant_id     uuid         not null,
    payload       clob         not null,
    status        varchar(16)  not null default 'PENDING',
    attempts      integer      not null default 0,
    last_error    varchar(500),
    created_at    timestamp with time zone not null default current_timestamp,
    published_at  timestamp with time zone
);

create table if not exists processed_event (
    event_id     uuid primary key,
    processed_at timestamp with time zone not null default current_timestamp
);
