-- notification-service: silo del tenant (aplicado por TenantSchemaMigrator a cada tenant).

-- Suscripciones de webhook. Los secretos HMAC se guardan cifrados en sobre (KEK del tenant), nunca en claro.
create table webhook_subscription (
    id                          uuid primary key,
    tenant_id                   uuid         not null,
    url                         varchar(2048) not null,
    events                      varchar(500) not null,
    active                      boolean      not null default true,
    secret_current              text         not null,
    secret_previous             text,
    secret_previous_expires_at  timestamp with time zone,
    created_by                  varchar(255) not null,
    created_at                  timestamp with time zone not null,
    rotated_at                  timestamp with time zone
);

create index idx_wh_active on webhook_subscription (tenant_id, active);

-- Politica del tenant: allowlist de hosts receptores y parametros de reintento (backoff configurable).
create table webhook_tenant_policy (
    tenant_id          uuid primary key,
    allowed_hosts      varchar(2000) not null default '',
    max_attempts       integer      not null,
    initial_backoff_ms bigint       not null,
    backoff_multiplier numeric(4, 2) not null,
    max_backoff_ms     bigint       not null,
    updated_at         timestamp with time zone not null
);

-- Historial de entregas. FALLIDO equivale al DLT: se reintenta a mano (POST .../retry).
create table webhook_delivery (
    id               uuid primary key,
    tenant_id        uuid         not null,
    webhook_id       uuid         not null,
    document_id      uuid         not null,
    source_event_id  uuid         not null,
    correlation_id   uuid         not null,
    event_type       varchar(64)  not null,
    payload          text         not null,
    status           varchar(16)  not null,
    attempts         integer      not null default 0,
    next_attempt_at  timestamp with time zone not null,
    last_attempt_at  timestamp with time zone,
    delivered_at     timestamp with time zone,
    last_http_status integer,
    error_code       varchar(64),
    error_msg        varchar(200),
    created_at       timestamp with time zone not null,
    constraint uq_wh_delivery_event unique (webhook_id, source_event_id)
);

create index idx_wh_delivery_doc on webhook_delivery (tenant_id, document_id);
create index idx_wh_status on webhook_delivery (status, next_attempt_at);
create index idx_wh_delivery_webhook on webhook_delivery (webhook_id, created_at);

-- Patron outbox e idempotencia de libs/events.
create table outbox (
    seq           bigint generated by default as identity,
    id            uuid primary key,
    partition_key varchar(255) not null,
    event_type    varchar(120) not null,
    tenant_id     uuid         not null,
    payload       text         not null,
    status        varchar(16)  not null default 'PENDING',
    attempts      integer      not null default 0,
    last_error    varchar(500),
    created_at    timestamp with time zone not null default now(),
    published_at  timestamp with time zone
);

create index idx_outbox_pending on outbox (status, created_at, id);

create table processed_event (
    tenant_id    uuid not null,
    event_id     uuid not null,
    processed_at timestamp with time zone not null default now(),
    primary key (tenant_id, event_id)
);
