-- chat-service: tablas del silo del tenant (aplicadas por tenant a cada silo).
-- Requiere PostgreSQL con pgvector. ${embedding_dimension} lo fija idp.chat.embedding-dimension.

create extension if not exists vector;

create table document_index_status (
    document_id uuid primary key,
    status      varchar(16) not null check (status in ('INDEXED')),
    indexed_at  timestamp with time zone not null
);

create table chunk (
    id          uuid primary key,
    document_id uuid         not null references document_index_status (document_id),
    ordinal     integer      not null check (ordinal >= 0),
    page_number integer      not null check (page_number >= 1),
    content     text         not null,
    embedding   vector(${embedding_dimension}) not null,
    constraint uq_chunk_document_ordinal unique (document_id, ordinal)
);

create index idx_chunk_document on chunk (document_id);
-- Distancia coseno: las consultas usan el operador <=> (similitud = 1 - distancia).
create index idx_chunk_embedding on chunk using hnsw (embedding vector_cosine_ops);

-- document_id no lleva FK: el documento vive en el document-service y la sesion puede abrirse antes de la
-- indexacion; la existencia y el acceso se verifican por DocumentAccessChecker (SEC-007).
create table chat_session (
    id          uuid primary key,
    document_id uuid         not null,
    user_id     varchar(128) not null,
    created_at  timestamp with time zone not null,
    active      boolean      not null default true
);

create index idx_chat_session_owner on chat_session (user_id, document_id);

create table chat_message (
    id                 uuid primary key,
    session_id         uuid        not null references chat_session (id),
    role               varchar(16) not null check (role in ('user', 'assistant')),
    content            text        not null,
    created_at         timestamp with time zone not null,
    -- Solo mensajes del asistente: respuesta a (mensaje del usuario) y resultado.
    reply_to           uuid references chat_message (id),
    outcome            varchar(16) check (outcome in ('ANSWERED', 'ABSTAINED', 'BLOCKED', 'CACHED')),
    -- Mensaje del asistente original de una respuesta servida desde cache.
    cached_from        uuid references chat_message (id),
    -- Solo mensajes del usuario: embedding de la pregunta (cache semantica sin recalcular el historial).
    question_embedding vector(${embedding_dimension})
);

create index idx_chat_message_session on chat_message (session_id, created_at);
create index idx_chat_message_reply on chat_message (reply_to);

create table citation (
    id          uuid primary key,
    message_id  uuid not null references chat_message (id),
    chunk_id    uuid not null references chunk (id),
    exact_quote text not null,
    ordinal     int  not null
);

create index idx_citation_message on citation (message_id);

-- Inmutabilidad (spec seccion 4): ni UPDATE, ni DELETE ni TRUNCATE sobre el historial y sus citas.
create function reject_mutation() returns trigger as $$
begin
    raise exception 'chat_message y citation son inmutables (%)', tg_op;
end;
$$ language plpgsql;

create trigger trg_chat_message_immutable before update or delete on chat_message
    for each row execute function reject_mutation();
create trigger trg_chat_message_no_truncate before truncate on chat_message
    for each statement execute function reject_mutation();
create trigger trg_citation_immutable before update or delete on citation
    for each row execute function reject_mutation();
create trigger trg_citation_no_truncate before truncate on citation
    for each statement execute function reject_mutation();

-- Patron outbox e idempotencia de libs/events.
create table outbox (
    seq           bigint generated by default as identity,
    id            uuid primary key,
    partition_key varchar(255) not null,
    event_type    varchar(120) not null,
    tenant_id     uuid         not null,
    payload       text         not null,
    status        varchar(16)  not null default 'PENDING',
    attempts      integer      not null default 0,
    last_error    varchar(500),
    created_at    timestamp with time zone not null default now(),
    published_at  timestamp with time zone
);

create index idx_outbox_pending on outbox (status, created_at, id);

create table processed_event (
    tenant_id    uuid not null,
    event_id     uuid not null,
    processed_at timestamp with time zone not null default now(),
    primary key (tenant_id, event_id)
);
