-- Outbox transaccional de quality-service (base de control, esquema propio): calidad.muestra_ciega_solicitada.
create table outbox (
    seq           bigint generated by default as identity,
    id            uuid primary key,
    partition_key varchar(255) not null,
    event_type    varchar(120) not null,
    tenant_id     uuid         not null,
    payload       text         not null,
    status        varchar(16)  not null default 'PENDING',
    attempts      integer      not null default 0,
    last_error    varchar(500),
    created_at    timestamp with time zone not null default now(),
    published_at  timestamp with time zone
);

create index idx_outbox_pending on outbox (status, created_at, id);

-- Identificador opaco de la muestra (viaja en el evento; es el id de la tarea ciega en review-service).
alter table qa_blind_sample add column sample_id uuid;
