-- review-service: tablas del silo del tenant (aplicadas por tenant-context a cada silo).
-- Los CHECK de dominio viven en postgresql/V2 (H2 de pruebas no soporta CHECK de texto entre sesiones).

create table review_task (
    id                  uuid primary key,
    tenant_id           uuid         not null,
    document_id         uuid         not null,
    correlation_id      uuid         not null,
    status              varchar(32)  not null,
    assignee_id         varchar(255),
    assigned_at         timestamp with time zone,
    first_reviewer_id   varchar(255),
    second_reviewer_id  varchar(255),
    critical_correction boolean      not null default false,
    sla_due_at          timestamp with time zone not null,
    escalation_level    integer      not null default 0,
    escalated_at        timestamp with time zone,
    completed_at        timestamp with time zone,
    cycle_seconds       bigint,
    created_at          timestamp with time zone not null,
    updated_at          timestamp with time zone not null
);

create index idx_review_task_document on review_task (document_id);
create index idx_review_task_queue on review_task (status, sla_due_at);
create index idx_review_task_assignee on review_task (assignee_id, status);

-- Cola por campo: un registro por campo dudoso a revisar.
create table review_field (
    id             uuid primary key,
    task_id        uuid         not null references review_task (id),
    field_name     varchar(200) not null,
    page           integer,
    bounding_box   varchar(200),
    original_value text,
    confidence     numeric(5, 4),
    critical       boolean      not null default false,
    status         varchar(16)  not null default 'PENDING',
    created_at     timestamp with time zone not null,
    constraint uq_review_field unique (task_id, field_name)
);

create index idx_review_field_task on review_field (task_id);

create table correction (
    id              uuid primary key,
    task_id         uuid         not null references review_task (id),
    field_name      varchar(200) not null,
    original_value  text,
    corrected_value text         not null,
    is_critical     boolean      not null,
    created_at      timestamp with time zone not null,
    created_by      varchar(255) not null,
    constraint uq_correction unique (task_id, field_name)
);

-- Patron outbox e idempotencia de libs/events.
create table outbox (
    seq           bigint generated by default as identity,
    id            uuid primary key,
    partition_key varchar(255) not null,
    event_type    varchar(120) not null,
    tenant_id     uuid         not null,
    payload       text         not null,
    status        varchar(16)  not null default 'PENDING',
    attempts      integer      not null default 0,
    last_error    varchar(500),
    created_at    timestamp with time zone not null default now(),
    published_at  timestamp with time zone
);

create index idx_outbox_pending on outbox (status, created_at, id);

create table processed_event (
    tenant_id    uuid not null,
    event_id     uuid not null,
    processed_at timestamp with time zone not null default now(),
    primary key (tenant_id, event_id)
);
