-- extraction-service: tablas del silo del tenant (aplicadas por tenant-context a cada esquema de tenant).

create table if not exists extraction (
    id               uuid primary key,
    document_id      uuid         not null,
    tenant_id        uuid         not null,
    status           varchar(32)  not null,
    typology_code    varchar(8),
    typology_version integer,
    model_version    varchar(255),
    prompt_version   varchar(100),
    overall_score    numeric(5, 4),
    tokens_in        integer      not null default 0,
    tokens_out       integer      not null default 0,
    cost_usd         numeric(12, 6) not null default 0,
    review_task_id   uuid,
    detail           varchar(200),
    created_at       timestamptz  not null default now()
);

create index if not exists idx_extraction_document on extraction (document_id);

create table if not exists field_value (
    id               uuid primary key,
    extraction_id    uuid         not null references extraction (id) on delete cascade,
    table_name       varchar(64),
    row_index        integer,
    field_name       varchar(64)  not null,
    value_text       text,
    confidence_score numeric(5, 4),
    evidence_page    integer,
    evidence_quote   text,
    bounding_box     jsonb,
    requires_review  boolean      not null default false,
    validation_error varchar(500)
);

create index if not exists idx_field_value_extraction on field_value (extraction_id);

-- SEC-049: registro firmado de prompt + configuracion + version de modelo por extraccion.
create table if not exists ai_execution_record (
    id            uuid primary key,
    extraction_id uuid         not null references extraction (id),
    payload       text         not null,
    signature     text         not null,
    key_id        varchar(100) not null,
    created_at    timestamptz  not null default now()
);

-- SEC-036 / AC-08: las versiones de modelo y prompt son inmutables una vez persistidas.
create or replace function extraction_immutable_versions() returns trigger as $$
begin
    if new.model_version is distinct from old.model_version
        or new.prompt_version is distinct from old.prompt_version then
        raise exception 'model_version y prompt_version son inmutables';
    end if;
    return new;
end;
$$ language plpgsql;

drop trigger if exists trg_extraction_immutable_versions on extraction;
create trigger trg_extraction_immutable_versions
    before update on extraction
    for each row execute function extraction_immutable_versions();

-- Patron outbox e idempotencia de libs/events.
create table if not exists outbox (
    seq bigint generated by default as identity,
    id            uuid primary key,
    partition_key varchar(255) not null,
    event_type    varchar(120) not null,
    tenant_id     uuid         not null,
    payload       text         not null,
    status        varchar(16)  not null default 'PENDING',
    attempts      integer      not null default 0,
    last_error    varchar(500),
    created_at    timestamptz  not null default now(),
    published_at  timestamptz
);

create index if not exists idx_outbox_pending on outbox (created_at, id) where status = 'PENDING';

create table if not exists processed_event (
    tenant_id    uuid not null,
    event_id     uuid not null,
    processed_at timestamptz not null default now(),
    primary key (tenant_id, event_id)
);
